
public class Vokabeltrainer_Oberflaeche extends javax.swing.JDialog {
    
    private Vokabeltrainer meinTrainer;

    public Vokabeltrainer_Oberflaeche(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        meinTrainer = new Vokabeltrainer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUeberschrift = new javax.swing.JLabel();
        jLabelNeueVokabel = new javax.swing.JLabel();
        jLabelInformatik = new javax.swing.JLabel();
        jLabelDeutsch = new javax.swing.JLabel();
        jTextNeuInfo = new javax.swing.JTextField();
        jTextNeuDeutsch = new javax.swing.JTextField();
        jNeueVokabel = new javax.swing.JToggleButton();
        jLabelVokabelSuchen = new javax.swing.JLabel();
        jTextSuche = new javax.swing.JTextField();
        jButtonSuche = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAusgabe = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonVokabelLoeschen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextAntwort = new javax.swing.JTextField();
        jTextLernenDt = new javax.swing.JTextField();
        jButtonUeberpruefen = new javax.swing.JButton();
        jButtonAusgabe = new javax.swing.JButton();
        jTextLaengeListe = new javax.swing.JTextField();
        jTextFieldneuesSynonym = new javax.swing.JTextField();
        jButtonSynonymHinzu = new javax.swing.JButton();
        jTextSuchergebnis = new javax.swing.JTextField();
        jTextAnzahlVokabeln = new javax.swing.JTextField();
        jButtonLos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelUeberschrift.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUeberschrift.setText("Vokabeltrainer");

        jLabelNeueVokabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNeueVokabel.setText("neue Vokabel");

        jLabelInformatik.setText("Informatik");

        jLabelDeutsch.setText("Deutsch");

        jTextNeuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNeuInfoActionPerformed(evt);
            }
        });
        jTextNeuInfo.setText("NeuInfo");
        jTextNeuDeutsch.setText("NeuDeutsch");

        jTextAntwort.setText("Antwort"); 
        jTextLernenDt.setText("LernenDt");
        
        jNeueVokabel.setText("Vokabel einfuegen");
        jNeueVokabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNeueVokabelActionPerformed(evt);
            }
        });

        jLabelVokabelSuchen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelVokabelSuchen.setText("Vokabel bearbeiten");

        jTextSuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSucheActionPerformed(evt);
            }
        });
        jTextSuche.setText("Suche");


        jButtonSuche.setText("Suche");
        jButtonSuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSucheActionPerformed(evt);
            }
        });

        jTextAreaAusgabe.setColumns(20);
        jTextAreaAusgabe.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAusgabe);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ausgabe");
        jTextAreaAusgabe.setText("Ausgabe");
        
        jButtonVokabelLoeschen.setText("Loeschen");
        jButtonVokabelLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVokabelLoeschenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Vokabeln lernen");

        jButtonUeberpruefen.setText("Pruefen");
        jButtonUeberpruefen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUeberpruefenActionPerformed(evt);
            }
        });

        jButtonAusgabe.setText("Alle Vokabeln anzeigen");
        jButtonAusgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAusgabeActionPerformed(evt);
            }
        });

        jTextLaengeListe.setText("0");
        jTextLaengeListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLaengeListeActionPerformed(evt);
            }
        });

        jButtonSynonymHinzu.setText("Synonym hinzufuegen");
        jButtonSynonymHinzu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSynonymHinzuActionPerformed(evt);
            }
        });

        jTextSuchergebnis.setEditable(false);
        jTextSuchergebnis.setText("Suchergebnis");
        jTextSuchergebnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSuchergebnisActionPerformed(evt);
            }
        });
        jTextFieldneuesSynonym.setText("neuesSynonym");
        jTextAnzahlVokabeln.setText("Anzahl");

        jButtonLos.setText("Los");
        jButtonLos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextAnzahlVokabeln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextLaengeListe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAusgabe))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelVokabelSuchen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextSuche, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSuche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVokabelLoeschen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextSuchergebnis, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldneuesSynonym, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSynonymHinzu))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelNeueVokabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUeberschrift))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextNeuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelInformatik))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextNeuDeutsch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jNeueVokabel))
                                .addComponent(jLabelDeutsch))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextLernenDt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextAntwort, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUeberpruefen))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelInformatik)
                        .addComponent(jLabelDeutsch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNeueVokabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUeberschrift, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNeuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNeueVokabel)
                            .addComponent(jTextNeuDeutsch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addComponent(jLabelVokabelSuchen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSuche)
                    .addComponent(jButtonVokabelLoeschen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldneuesSynonym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSynonymHinzu)
                    .addComponent(jTextSuchergebnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAnzahlVokabeln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLernenDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAntwort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUeberpruefen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAusgabe)
                    .addComponent(jTextLaengeListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNeuInfoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
    }
    
    private void jTextSucheActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonSucheActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextSuche.setText("Hallo");
    }

    private void jNeueVokabelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        meinTrainer.neueVokabelHinzufuegen(jTextNeuInfo.getText(),jTextNeuDeutsch.getText());
    }

    private void jButtonAusgabeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
      
        jTextAreaAusgabe.setText(meinTrainer.returnAll());
    }

    private void jButtonVokabelLoeschenActionPerformed(java.awt.event.ActionEvent evt) {        
        // TODO add your handling code here:
    
    }

    private void jTextLaengeListeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonSynonymHinzuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
       
    }

    private void jTextSuchergebnisActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    private void jButtonLosActionPerformed(java.awt.event.ActionEvent evt) {
        jTextLernenDt.setText(VokabelTrainer.vokabelAbfragen())
    }

    private void jButtonUeberpruefenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
      
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vokabeltrainer_Oberflaeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vokabeltrainer_Oberflaeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vokabeltrainer_Oberflaeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vokabeltrainer_Oberflaeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vokabeltrainer_Oberflaeche dialog = new Vokabeltrainer_Oberflaeche(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAusgabe;
    private javax.swing.JButton jButtonLos;
    private javax.swing.JButton jButtonSuche;
    private javax.swing.JButton jButtonSynonymHinzu;
    private javax.swing.JButton jButtonUeberpruefen;
    private javax.swing.JButton jButtonVokabelLoeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDeutsch;
    private javax.swing.JLabel jLabelInformatik;
    private javax.swing.JLabel jLabelNeueVokabel;
    private javax.swing.JLabel jLabelUeberschrift;
    private javax.swing.JLabel jLabelVokabelSuchen;
    private javax.swing.JToggleButton jNeueVokabel;
    private javax.swing.JScrollPane jScrollPane1;

    //neue Vokabel
    private javax.swing.JTextField jTextNeuInfo;
    private javax.swing.JTextField jTextNeuDeutsch;
    // Vokabel bearbeiten
    private javax.swing.JTextField jTextSuche;
    private javax.swing.JTextField jTextSuchergebnis;
    private javax.swing.JTextField jTextFieldneuesSynonym;
    // Vokabeln lernen
    private javax.swing.JTextField jTextAnzahlVokabeln;
    private javax.swing.JTextField jTextLernenDt;
    private javax.swing.JTextField jTextAntwort;
    // Ausgabe
    private javax.swing.JTextField jTextLaengeListe;
    private javax.swing.JTextArea jTextAreaAusgabe;    
    // End of variables declaration//GEN-END:variables  
}
